### ISSUE TITLE
JOSS review - Configuration file and more

### ISSUE THREAD

**Issue by wcwitt** [ICAMS/strucscan#65]
Part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/4719). These comments refer to the "[Getting Started](https://strucscan.readthedocs.io/en/latest/examples/01_getting_started.html)" part of the docs, particularly this section:

> This exmaple illustrates a sample workflow using the pre-implemented dummy engine. To make use of it please configure the .strucscan configuration file and copy it in you home directory. You can use the template that comes by default with the repository and link the absoulte pathes to the structure and resource repository to the default ones from the repository.
> 
> ! cat ../.strucscan
> PROJECT_PATH: "data"    # corresponds to the top node of your data tree
> STRUCTURES_PATH: "structures"
> RESOURCE_PATH: "resources"
> 
> DEBUG: FALSE                # Default: FALSE
> STRUCT_FILE_FORMAT: cfg     # Default: cfg
> SLEEP_TIME: 45              # Default: 45
> In general, you might want to adapt the .strucscan to your own structure and resource directory and set up a resource directory accordingly. For now, you do not need to worry about it and we will discuss it later.

It's likely I haven't understood everything perfectly, but to run the Dummy example I needed to put this file in my home directory and update the PROJECT_PATH, STRUCTURES_PATH, and RESOURCE_PATH lines. The docs do say this, but I found the instructions a bit confusing and it took me several tries to get it right.

Some questions/requests:

* Is a global configuration file the only way to provide these settings? It seems that would prevent simultaneous calls to `strucscan` for separate projects. But maybe I'm missing something.
* I think it would be useful at this stage to provide short explanations for what is contained in STRUCTURES and RESOURCES. It seems if I were getting started, the first thing I would need to do is create these directories and populate them for my needs, but that's not immediately clear from the Getting Started docs. (The README does have some of this information.)
* Why are the `structures` and `resources` in the top-level repo? Would it be more clear to have them inside `examples`? But again, it feels like I may be missing something - so a bit more clarity in the Getting Started section would be useful.

**Comment by thohamm** [comment]
Thank you for your comments, we really appreciate your feedback that helps us to clarify the documentation.

1. The `.strucscan` configuration file is indeed the central way to configure the path to the project tree. Our aim is to provide a top folder for storing the data of all projects. This does not prevent the user  from using strucscan for different projects simultaneously as they will be stored below the specified projects top node and may use different engines, structures, elements, etc as specified in the individual input.yaml files.

2. We agree and synchronized the content of the README with the documentation and now give information on the structure and resource directories also in the Getting Started docs.

3. The structures and resources folders are meant as top nodes for collecting input structures to be used in different projects. Taking DFT calculations as example, one typically wants to run equation-of-state calculations for the same set of crystal structures (fcc, bcc, hcp, ..) for different chemical elements (Al, Ni, ..). Having structures and resources at the top level, they can grow over time in the different projects. To be clearer for the examples, we now provide the structure and resource directory also in the examples directory.
